
###############################################################################
#
# Inclusive Makefile for the libonlp-powerpc-dm4370 module.
#
# Autogenerated 2018-11-05 15:22:20.005844
#
###############################################################################
libonlp-powerpc-dm4370_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

