
###############################################################################
#
# Inclusive Makefile for the powerpc_dm4370 module.
#
# Autogenerated 2018-11-05 12:41:54.910493
#
###############################################################################
powerpc_dm4370_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(powerpc_dm4370_BASEDIR)module/make.mk
include $(powerpc_dm4370_BASEDIR)module/auto/make.mk
include $(powerpc_dm4370_BASEDIR)module/src/make.mk

